# Generated by Django 4.2.7 on 2025-09-13 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IndexRPS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index_code", models.CharField(max_length=20, verbose_name="指数代码")),
                ("index_name", models.CharField(max_length=50, verbose_name="指数简称")),
                ("period", models.IntegerField(verbose_name="周期(天)")),
                (
                    "change_percent",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="涨跌幅(%)"
                    ),
                ),
                (
                    "rps_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="RPS值"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "指数RPS强度排名",
                "verbose_name_plural": "指数RPS强度排名",
                "db_table": "index_rps",
                "ordering": ["-created_at", "-rps_value"],
                "unique_together": {("index_code", "period", "created_at")},
            },
        ),
    ]
