# Generated by Django 4.2.7 on 2025-11-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock_strategy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockSelectionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("market", models.CharField(max_length=20, verbose_name="市场")),
                ("code", models.CharField(max_length=20, verbose_name="代码")),
                ("name", models.CharField(max_length=50, verbose_name="名称")),
                ("trade_date", models.DateField(verbose_name="交易日")),
                (
                    "predict_rise_prob",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="预测上涨概率(%)"
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="置信度(%)"
                    ),
                ),
                (
                    "prediction_type",
                    models.CharField(max_length=30, verbose_name="预测类型"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "选股记录",
                "verbose_name_plural": "选股记录",
                "db_table": "stock_selection_record",
                "ordering": ["-trade_date", "-predict_rise_prob"],
                "unique_together": {("code", "trade_date")},
            },
        ),
    ]
