# Generated by Django 4.2.7 on 2025-11-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock_strategy", "0002_stockselectionrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockselectionrecord",
            name="actual_rise_ratio_5d",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="5日实际上涨比例(%)",
            ),
        ),
    ]
