# Generated by Codex on 2026-09-06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitationcode",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_invitations",
                to="user_management.user",
                verbose_name="创建者",
            ),
        ),
        migrations.CreateModel(
            name="SiteVisitCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        default="site_total",
                        max_length=50,
                        unique=True,
                        verbose_name="计数键",
                    ),
                ),
                (
                    "total_count",
                    models.PositiveBigIntegerField(default=0, verbose_name="总访问数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "站点访问计数",
                "verbose_name_plural": "站点访问计数",
                "ordering": ["key"],
            },
        ),
    ]
