# Generated by Django 4.2.7 on 2025-10-19 02:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock_market", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndexBasicData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="指数代码，如'000001.SH'",
                        max_length=20,
                        unique=True,
                        verbose_name="代码",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="指数名称，如'上证指数'", max_length=100, verbose_name="名称"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "指数基础数据",
                "verbose_name_plural": "指数基础数据",
                "db_table": "stock_market_index_basic_data",
                "ordering": ["code"],
            },
        ),
    ]
