# Generated by Django 4.2.7 on 2025-10-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock_market", "0002_indexbasicdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndexHighLowStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="数据统计的日期", verbose_name="统计日期")),
                (
                    "index_code",
                    models.CharField(
                        choices=[
                            ("all", "全部A股"),
                            ("sz50", "上证50"),
                            ("hs300", "沪深300"),
                            ("zz500", "中证500"),
                        ],
                        help_text="指数类型：all-全部A股, sz50-上证50, hs300-沪深300, zz500-中证500",
                        max_length=10,
                        verbose_name="指数代码",
                    ),
                ),
                (
                    "close",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="当日收盘价",
                        max_digits=10,
                        null=True,
                        verbose_name="收盘价",
                    ),
                ),
                (
                    "high20",
                    models.IntegerField(
                        blank=True,
                        help_text="创20日新高的股票数量",
                        null=True,
                        verbose_name="20日新高数量",
                    ),
                ),
                (
                    "low20",
                    models.IntegerField(
                        blank=True,
                        help_text="创20日新低的股票数量",
                        null=True,
                        verbose_name="20日新低数量",
                    ),
                ),
                (
                    "high60",
                    models.IntegerField(
                        blank=True,
                        help_text="创60日新高的股票数量",
                        null=True,
                        verbose_name="60日新高数量",
                    ),
                ),
                (
                    "low60",
                    models.IntegerField(
                        blank=True,
                        help_text="创60日新低的股票数量",
                        null=True,
                        verbose_name="60日新低数量",
                    ),
                ),
                (
                    "high120",
                    models.IntegerField(
                        blank=True,
                        help_text="创120日新高的股票数量",
                        null=True,
                        verbose_name="120日新高数量",
                    ),
                ),
                (
                    "low120",
                    models.IntegerField(
                        blank=True,
                        help_text="创120日新低的股票数量",
                        null=True,
                        verbose_name="120日新低数量",
                    ),
                ),
                (
                    "rise_fall_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="涨的数量/(涨+跌数量)，范围0-1",
                        max_digits=5,
                        null=True,
                        verbose_name="涨跌比",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "指数涨跌统计",
                "verbose_name_plural": "指数涨跌统计",
                "db_table": "stock_market_index_high_low_statistics",
                "ordering": ["-date", "index_code"],
                "unique_together": {("date", "index_code")},
            },
        ),
    ]
