# Generated by Django 4.2.7 on 2025-10-19 08:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stock_market", "0003_indexhighlowstatistics"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="indexhighlowstatistics",
            name="rise_fall_ratio",
        ),
    ]
