# Generated by Django 4.2.7 on 2026-07-11 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_market', '0005_stockmarketfundflow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockMarketFundFlow',
        ),
    ]
