# Generated by Django 4.2.7 on 2025-09-19 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StrategyConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="策略名称"),
                ),
                ("display_name", models.CharField(max_length=200, verbose_name="显示名称")),
                ("description", models.TextField(verbose_name="策略描述")),
                (
                    "strategy_class",
                    models.CharField(max_length=200, verbose_name="策略类名"),
                ),
                ("default_params", models.JSONField(default=dict, verbose_name="默认参数")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "策略配置",
                "verbose_name_plural": "策略配置",
                "db_table": "quantitative_strategy_config",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StrategyPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "strategy_name",
                    models.CharField(max_length=100, verbose_name="策略名称"),
                ),
                ("stock_code", models.CharField(max_length=20, verbose_name="股票代码")),
                ("period_start", models.DateField(verbose_name="统计开始日期")),
                ("period_end", models.DateField(verbose_name="统计结束日期")),
                (
                    "avg_return",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="平均收益率"
                    ),
                ),
                (
                    "avg_sharpe",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="平均夏普比率",
                    ),
                ),
                (
                    "avg_drawdown",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="平均最大回撤",
                    ),
                ),
                (
                    "success_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="成功率"
                    ),
                ),
                (
                    "total_backtests",
                    models.IntegerField(default=0, verbose_name="回测总数"),
                ),
                (
                    "successful_backtests",
                    models.IntegerField(default=0, verbose_name="成功回测数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "策略性能统计",
                "verbose_name_plural": "策略性能统计",
                "db_table": "quantitative_strategy_performance",
                "ordering": ["-updated_at"],
                "unique_together": {
                    ("strategy_name", "stock_code", "period_start", "period_end")
                },
            },
        ),
        migrations.CreateModel(
            name="BacktestTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(max_length=100, unique=True, verbose_name="任务ID"),
                ),
                (
                    "strategy_name",
                    models.CharField(max_length=100, verbose_name="策略名称"),
                ),
                ("stock_code", models.CharField(max_length=20, verbose_name="股票代码")),
                (
                    "stock_name",
                    models.CharField(blank=True, max_length=100, verbose_name="股票名称"),
                ),
                ("start_date", models.DateField(verbose_name="开始日期")),
                ("end_date", models.DateField(verbose_name="结束日期")),
                (
                    "initial_cash",
                    models.DecimalField(
                        decimal_places=2,
                        default=100000,
                        max_digits=15,
                        verbose_name="初始资金",
                    ),
                ),
                (
                    "commission",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.001,
                        max_digits=6,
                        verbose_name="手续费率",
                    ),
                ),
                (
                    "strategy_params",
                    models.JSONField(default=dict, verbose_name="策略参数"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("running", "运行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="错误信息")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "回测任务",
                "verbose_name_plural": "回测任务",
                "db_table": "quantitative_backtest_task",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BacktestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "initial_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="初始资金"
                    ),
                ),
                (
                    "final_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="最终资金"
                    ),
                ),
                (
                    "total_return",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="总收益率"
                    ),
                ),
                (
                    "annual_return",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="年化收益率"
                    ),
                ),
                (
                    "sharpe_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="夏普比率",
                    ),
                ),
                (
                    "max_drawdown",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="最大回撤",
                    ),
                ),
                (
                    "volatility",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="波动率",
                    ),
                ),
                ("total_trades", models.IntegerField(default=0, verbose_name="总交易次数")),
                (
                    "winning_trades",
                    models.IntegerField(default=0, verbose_name="盈利交易次数"),
                ),
                (
                    "losing_trades",
                    models.IntegerField(default=0, verbose_name="亏损交易次数"),
                ),
                (
                    "win_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="胜率",
                    ),
                ),
                ("daily_returns", models.JSONField(default=list, verbose_name="每日收益率")),
                (
                    "portfolio_values",
                    models.JSONField(default=list, verbose_name="组合价值序列"),
                ),
                ("trade_records", models.JSONField(default=list, verbose_name="交易记录")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quantitative_strategy.backtesttask",
                        verbose_name="回测任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "回测结果",
                "verbose_name_plural": "回测结果",
                "db_table": "quantitative_backtest_result",
                "ordering": ["-created_at"],
            },
        ),
    ]
