# Generated by Django 4.2.7 on 2025-09-20 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0001_initial"),
        ("quantitative_strategy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backtesttask",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user_management.user",
                verbose_name="用户",
            ),
        ),
    ]
