# Generated by Django 4.2.7 on 2025-09-29 03:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quantitative_strategy", "0002_alter_backtesttask_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="backtestresult",
            name="chart_image",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="回测图表路径"
            ),
        ),
    ]
