# Generated by Django 4.2.7 on 2025-09-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quantitative_strategy", "0003_backtestresult_chart_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="backtestresult",
            name="observer_data",
            field=models.JSONField(
                default=dict,
                help_text="包含Broker、BuySell、Trades、TimeReturn、DrawDown、Benchmark等观测器数据",
                verbose_name="观测器数据",
            ),
        ),
    ]
