# Generated by Django 4.2.7 on 2025-09-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quantitative_strategy", "0004_backtestresult_observer_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="backtestresult",
            name="indicator_data",
            field=models.JSONField(
                default=dict, help_text="包含技术指标计算结果", verbose_name="指标数据"
            ),
        ),
        migrations.AddField(
            model_name="backtestresult",
            name="raw_data",
            field=models.JSONField(
                default=dict, help_text="包含OHLCV等原始市场数据", verbose_name="原始数据"
            ),
        ),
    ]
