# Generated by Django 4.2.7 on 2025-11-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quantitative_strategy", "0005_backtestresult_indicator_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="backtesttask",
            name="frequency",
            field=models.CharField(
                default="daily",
                help_text="数据频率类型：daily（日频，默认）或 weekly（周频）",
                max_length=20,
                verbose_name="数据频率",
            ),
        ),
    ]
