# Generated by Django 4.2.7 on 2025-11-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quantitative_strategy", "0006_backtesttask_frequency"),
    ]

    operations = [
        migrations.AddField(
            model_name="backtesttask",
            name="data_source",
            field=models.CharField(
                choices=[("stock", "个股"), ("etf", "ETF")],
                default="stock",
                help_text="标的类型：stock（个股）或 etf（基金）；当为etf时，stock_code字段存放ETF ts_code",
                max_length=20,
                verbose_name="数据来源",
            ),
        ),
    ]