# Generated by Django 4.2.7 on 2025-10-24 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user_management", "0001_initial"),
        ("indival_stock_data", "0011_alter_stocktag_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Holding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="所属行业"
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[("HELD", "持有"), ("WATCHED", "关注")],
                        default="WATCHED",
                        max_length=10,
                        verbose_name="关系类型",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_holdings",
                        to="indival_stock_data.individualstock",
                        verbose_name="股票",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holdings",
                        to="user_management.user",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "个人持有/关注股票",
                "verbose_name_plural": "个人持有/关注股票",
                "ordering": ["-created_at"],
                "unique_together": {("user", "stock", "relation_type")},
            },
        ),
    ]
