# Generated by Django 4.2.7 on 2025-09-14 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stock_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndustrySector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="板块代码"),
                ),
                ("name", models.CharField(max_length=50, verbose_name="板块名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="板块描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "行业板块",
                "verbose_name_plural": "行业板块",
                "db_table": "industry_sector",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="IndustrySectorDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="交易日期")),
                (
                    "open_price",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="开盘价"
                    ),
                ),
                (
                    "close_price",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="收盘价"
                    ),
                ),
                (
                    "high_price",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="最高价"
                    ),
                ),
                (
                    "low_price",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="最低价"
                    ),
                ),
                (
                    "change_percent",
                    models.DecimalField(
                        decimal_places=3, max_digits=8, verbose_name="涨跌幅(%)"
                    ),
                ),
                (
                    "change_amount",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="涨跌额"
                    ),
                ),
                ("total_volume", models.BigIntegerField(verbose_name="总成交量(手)")),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="总成交额(元)"
                    ),
                ),
                (
                    "total_market_cap",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="总市值",
                    ),
                ),
                (
                    "amplitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=8,
                        null=True,
                        verbose_name="振幅(%)",
                    ),
                ),
                (
                    "turnover_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=8,
                        null=True,
                        verbose_name="平均换手率(%)",
                    ),
                ),
                ("rising_stocks", models.IntegerField(verbose_name="上涨股票数")),
                ("falling_stocks", models.IntegerField(verbose_name="下跌股票数")),
                (
                    "flat_stocks",
                    models.IntegerField(blank=True, null=True, verbose_name="平盘股票数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_data",
                        to="stock_data.industrysector",
                        verbose_name="所属板块",
                    ),
                ),
            ],
            options={
                "verbose_name": "行业板块日频数据",
                "verbose_name_plural": "行业板块日频数据",
                "db_table": "industry_sector_daily",
                "ordering": ["-date", "sector"],
                "indexes": [
                    models.Index(
                        fields=["sector", "-date"],
                        name="industry_se_sector__5046c5_idx",
                    ),
                    models.Index(fields=["-date"], name="industry_se_date_2ed900_idx"),
                ],
                "unique_together": {("sector", "date")},
            },
        ),
    ]
