# Generated by Django 4.2.7 on 2025-09-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock_data", "0002_industrysector_industrysectordaily"),
    ]

    operations = [
        migrations.AddField(
            model_name="industrysector",
            name="change_amount",
            field=models.FloatField(blank=True, null=True, verbose_name="涨跌额"),
        ),
        migrations.AddField(
            model_name="industrysector",
            name="change_percent",
            field=models.FloatField(blank=True, null=True, verbose_name="涨跌幅"),
        ),
        migrations.AddField(
            model_name="industrysector",
            name="fall_count",
            field=models.IntegerField(blank=True, null=True, verbose_name="下跌家数"),
        ),
        migrations.AddField(
            model_name="industrysector",
            name="latest_price",
            field=models.FloatField(blank=True, null=True, verbose_name="最新价"),
        ),
        migrations.AddField(
            model_name="industrysector",
            name="leading_stock",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="领涨股票"
            ),
        ),
        migrations.AddField(
            model_name="industrysector",
            name="leading_stock_change_percent",
            field=models.FloatField(blank=True, null=True, verbose_name="领涨股票涨跌幅"),
        ),
        migrations.AddField(
            model_name="industrysector",
            name="rise_count",
            field=models.IntegerField(blank=True, null=True, verbose_name="上涨家数"),
        ),
        migrations.AddField(
            model_name="industrysector",
            name="total_market_value",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="总市值"),
        ),
        migrations.AddField(
            model_name="industrysector",
            name="turnover_rate",
            field=models.FloatField(blank=True, null=True, verbose_name="换手率"),
        ),
    ]
