# Generated by Django 4.2.7 on 2025-11-16 01:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EtfDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ts_code", models.CharField(max_length=20, verbose_name="TS代码")),
                ("trade_date", models.DateField(verbose_name="交易日期")),
                (
                    "open",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="开盘价"
                    ),
                ),
                (
                    "high",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="最高价"
                    ),
                ),
                (
                    "low",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="最低价"
                    ),
                ),
                (
                    "close",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="收盘价"
                    ),
                ),
                (
                    "pre_close",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="昨收盘价",
                    ),
                ),
                (
                    "change",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="涨跌额",
                    ),
                ),
                (
                    "pct_chg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        verbose_name="涨跌幅(%)",
                    ),
                ),
                ("vol", models.BigIntegerField(verbose_name="成交量(手)")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="成交额(元)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "ETF 日线行情",
                "verbose_name_plural": "ETF 日线行情",
                "db_table": "etf_daily",
                "ordering": ["-trade_date", "ts_code"],
                "indexes": [
                    models.Index(
                        fields=["ts_code", "-trade_date"],
                        name="etf_daily_ts_code_80ccef_idx",
                    ),
                    models.Index(
                        fields=["-trade_date"], name="etf_daily_trade_d_895bbe_idx"
                    ),
                ],
                "unique_together": {("ts_code", "trade_date")},
            },
        ),
        migrations.CreateModel(
            name="EtfBasic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ts_code",
                    models.CharField(max_length=20, unique=True, verbose_name="TS代码"),
                ),
                (
                    "csname",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="中文简称"
                    ),
                ),
                ("extname", models.CharField(max_length=100, verbose_name="ETF扩位简称")),
                (
                    "cname",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="基金中文全称"
                    ),
                ),
                (
                    "index_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="跟踪指数代码"
                    ),
                ),
                (
                    "index_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="跟踪指数名称"
                    ),
                ),
                (
                    "exchange",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="交易所"
                    ),
                ),
                (
                    "list_status",
                    models.CharField(
                        choices=[("L", "上市"), ("D", "退市"), ("P", "待上市")],
                        default="L",
                        max_length=1,
                        verbose_name="上市状态",
                    ),
                ),
                (
                    "setup_date",
                    models.DateField(blank=True, null=True, verbose_name="设立日期"),
                ),
                (
                    "list_date",
                    models.DateField(blank=True, null=True, verbose_name="上市日期"),
                ),
                (
                    "delist_date",
                    models.DateField(blank=True, null=True, verbose_name="退市日期"),
                ),
                (
                    "etf_type",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="ETF类型"
                    ),
                ),
                (
                    "mgr_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="基金管理人简称"
                    ),
                ),
                (
                    "custod_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="基金托管人名称"
                    ),
                ),
                (
                    "mgt_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        verbose_name="管理费率",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "ETF 基本信息",
                "verbose_name_plural": "ETF 基本信息",
                "db_table": "etf_basic",
                "ordering": ["ts_code"],
                "indexes": [
                    models.Index(
                        fields=["ts_code"], name="etf_basic_ts_code_106e0f_idx"
                    ),
                    models.Index(
                        fields=["exchange"], name="etf_basic_exchang_cbb8ad_idx"
                    ),
                    models.Index(
                        fields=["list_status"], name="etf_basic_list_st_e0513a_idx"
                    ),
                ],
            },
        ),
    ]
