"""Django settings for stock_data_service project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'dev-secret-key-change-this')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = ['*']

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'django_crontab',
    'industry_stock_data',
    'cctv_news',
    'stock_strategy',
    'user_management',
    'scheduled_tasks',
    'forum',
    'indival_stock_data',
    'quantitative_strategy',
    'stock_market',
    'django_comment_migrate',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'user_management.middleware.AuthenticationMiddleware',
]

ROOT_URLCONF = 'stock_data_service.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'stock_data_service.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME', 'stock_db'),
        'USER': os.environ.get('DB_USER', 'hc'),
        'PASSWORD': os.environ.get('DB_PASSWORD', '1125677925'),
        'HOST': os.environ.get('DB_HOST', '47.120.53.64'),
        'PORT': os.environ.get('DB_PORT', '3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/
LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS settings
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

# CSRF settings
CSRF_TRUSTED_ORIGINS = ['http://localhost:5174', 'http://localhost:5173']

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DATETIME_FORMAT': '%Y-%m-%dT%H:%M:%S',
    'DATE_FORMAT': '%Y-%m-%d',
}

# Redis配置（预留）
# REDIS_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')

# # 缓存配置
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.redis.RedisCache',
#         'LOCATION': REDIS_URL,
#         'TIMEOUT': int(os.environ.get('CACHE_TIMEOUT', 300)),
#     }
# }

# 日志配置
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
}

# 股票数据API配置
STOCK_API_KEY = os.environ.get('STOCK_API_KEY')
STOCK_API_BASE_URL = os.environ.get('STOCK_API_BASE_URL', 'https://api.example.com')

# 数据更新频率（秒）
DATA_UPDATE_INTERVAL = int(os.environ.get('DATA_UPDATE_INTERVAL', 60))

# 股票数据缓存时间（秒）
STOCK_CACHE_TIMEOUT = int(os.environ.get('STOCK_CACHE_TIMEOUT', 300))
STOCK_REQUEST_TIMEOUT = int(os.environ.get('STOCK_REQUEST_TIMEOUT', 30))
STOCK_MAX_RETRIES = int(os.environ.get('STOCK_MAX_RETRIES', 3))

# 定时任务配置
# CRONJOBS = [
#     # 每天早上9:00更新个股列表
#     ('0 9 * * *', 'scheduled_tasks.individual_stock_tasks.fetch_individual_stocks'),
#     # 交易时间内每5分钟更新个股实时行情（9:30-11:30, 13:00-15:00）
#     ('*/5 9-11,13-15 * * 1-5', 'scheduled_tasks.individual_stock_tasks.update_individual_stock_realtime'),
#     # 每天收盘后更新个股日频数据
#     ('30 15 * * 1-5', 'scheduled_tasks.individual_stock_tasks.update_individual_stock_daily_data'),
# ]

# API限流配置
API_RATE_LIMIT = os.environ.get('API_RATE_LIMIT', '100/hour')

# 创建日志目录
log_dir = BASE_DIR / 'logs'
log_dir.mkdir(exist_ok=True)

# Django Crontab配置
CRONJOBS = [
    # 默认的系统维护任务
    ('0 2 * * *', 'scheduled_tasks.tasks.cleanup_old_logs'),  # 每天凌晨2点清理旧日志
    ('*/30 * * * *', 'scheduled_tasks.tasks.check_task_status'),  # 每30分钟检查任务状态

    # 新闻资讯
    ('25 20,21 * * *', 'scheduled_tasks.tasks.fetch_cctv_news', f'>> {BASE_DIR}/logs/cctv_news.log 2>&1'),  # 每天晚上9:04爬取新闻联播
    ('35 20,21 * * *', 'scheduled_tasks.tasks.analyze_cctv_news', f'>> {BASE_DIR}/logs/cctv_news_analysis.log 2>&1'),  # 每天晚上10:00分析新闻联播

    # 行业板块
    ('25 16,17,18,19 * * *', 'scheduled_tasks.stock_data_query_tasks.industry_sector_tasks.fetch_industry_sectors', f'>> {BASE_DIR}/logs/industry_sector_list.log 2>&1'),  # 每周一至周五9:00更新行业板块列表
    ('45 1,4,6,8 * * *', 'scheduled_tasks.stock_data_query_tasks.industry_sector_tasks.mark_stock_industry', f'>> {BASE_DIR}/logs/mark_stock_industry.log 2>&1'),  # 每周一至周五16:00-22:00更新行业板块实时数据
    ('1 16,17,18,19 * * *', 'scheduled_tasks.stock_data_query_tasks.industry_sector_tasks.update_industry_sector_daily_data', f'>> {BASE_DIR}/logs/fetch_industry_sector_daily_data.log 2>&1'),  # 每天16-22点每小时更新行业板块数据
    ('30 19 * * *', 'scheduled_tasks.stock_data_query_tasks.industry_sector_tasks.update_industry_sector_fund_flow_data', f'>> {BASE_DIR}/logs/update_industry_sector_fund_flow_data.log 2>&1'),  # 每天16-22点每小时更新行业板块资金流数据

    # 大盘数据
    ('45 19 * * *', 'scheduled_tasks.stock_data_query_tasks.market_tasks.fetch_stock_market_fund_flow', f'>> {BASE_DIR}/logs/fetch_stock_market_fund_flow.log 2>&1'),  # 每天16-22点每小时更新大盘资金流数据
    ('15 20 * * *', 'scheduled_tasks.stock_data_query_tasks.market_tasks.fetch_all_index_high_low_statistics', f'>> {BASE_DIR}/logs/fetch_all_index_high_low_statistics.log 2>&1'),  # 每天16-22点每小时更新大盘日频数据

    # 个股数据 
    ('59 1,12,20 * * *', 'scheduled_tasks.stock_data_query_tasks.individual_stock_tasks.fetch_individual_stocks', f'>> {BASE_DIR}/logs/fetch_individual_stock_list.log 2>&1'), 
    ('40 16,23 * * *', 'scheduled_tasks.stock_data_query_tasks.individual_stock_tasks.update_individual_stock_daily_data', f'>> {BASE_DIR}/logs/update_individual_stock_daily_data.log 2>&1'),
    ('20 18 * * *', 'scheduled_tasks.stock_data_query_tasks.individual_stock_tasks.update_index_stock_daily_data', f'>> {BASE_DIR}/logs/update_index_stock_daily_data.log 2>&1'),
]

# Crontab配置
CRONTAB_LOCK_JOBS = True
CRONTAB_COMMAND_PREFIX = f'PYTHONPATH={BASE_DIR}'
CRONTAB_DJANGO_SETTINGS_MODULE = 'stock_data_service.settings'

# 注释迁移插件配置
DCM_COMMENT_KEY = 'verbose_name'  # 将字段 verbose_name 作为列注释来源
DCM_TABLE_COMMENT_KEY = 'verbose_name'  # 将模型 Meta.verbose_name 作为表注释来源
DCM_COMMENT_APP = ['indival_stock_data']  # 仅迁移该 app 的注释