"""Django settings for stock_data_service project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'dev-secret-key-change-this')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = ['*']

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'drf_spectacular',
    'industry_stock_data',
    'stock_strategy',
    'user_management',
    'index_data',
    'indival_stock_data',
    'stock_market',
    'django_comment_migrate',
    'etfapp',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'stock_data_service.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'stock_data_service.wsgi.application'
ASGI_APPLICATION = 'stock_data_service.asgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
DB_PASSWORD = os.environ.get('DB_PASSWORD')
if not DB_PASSWORD:
    raise ValueError('DB_PASSWORD environment variable is required')

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME', 'stock_db'),
        'USER': os.environ.get('DB_USER', 'hc'),
        'PASSWORD': DB_PASSWORD,
        'HOST': os.environ.get('DB_HOST', '47.120.53.64'),
        'PORT': os.environ.get('DB_PORT', '3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/
LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS settings
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

# CSRF settings
CSRF_TRUSTED_ORIGINS = ['http://localhost:5174', 'http://localhost:5173']

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DATETIME_FORMAT': '%Y-%m-%dT%H:%M:%S',
    'DATE_FORMAT': '%Y-%m-%d',
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# drf-spectacular 配置
SPECTACULAR_SETTINGS = {
    'TITLE': '股票数据服务 OpenAPI 文档',
    'DESCRIPTION': '统一响应格式的 Django REST API 文档',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
}

# Redis配置（预留）
# REDIS_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')

# # 缓存配置
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.redis.RedisCache',
#         'LOCATION': REDIS_URL,
#         'TIMEOUT': int(os.environ.get('CACHE_TIMEOUT', 300)),
#     }
# }

# 日志配置
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
}

# 股票数据API配置
STOCK_API_KEY = os.environ.get('STOCK_API_KEY')
STOCK_API_BASE_URL = os.environ.get('STOCK_API_BASE_URL', 'https://api.example.com')

# AI 模型配置 - 通过 AI_MODEL_PROVIDER 切换 (qwen2api | deepseek | doubao_seed)

# Qwen2API（OpenAI 兼容，参考 https://github.com/smanx/qwen2api）
# 公开 Netlify 服务可免 key；BASE_URL 需含 /v1
QWEN2API_API_KEY = os.environ.get('QWEN2API_API_KEY', '')
QWEN2API_BASE_URL = os.environ.get(
    'QWEN2API_BASE_URL',
    'https://qwen2api-n.smanx.xx.kg/v1',
)
QWEN2API_MODEL_NAME = os.environ.get('QWEN2API_MODEL_NAME', 'qwen3.5-plus')

# DeepSeek 配置
DEEPSEEK_API_KEY = os.environ.get('DEEPSEEK_API_KEY')
DEEPSEEK_BASE_URL = os.environ.get('DEEPSEEK_BASE_URL', 'https://api.deepseek.com/v1')
DEEPSEEK_MODEL_NAME = os.environ.get('DEEPSEEK_MODEL_NAME', 'deepseek-v4-flash')
DEEPSEEK_THINKING_TYPE = os.environ.get('DEEPSEEK_THINKING_TYPE', 'enabled')
DEEPSEEK_REASONING_EFFORT = os.environ.get('DEEPSEEK_REASONING_EFFORT', 'high')

# 豆包 Seed 配置（多模态，OpenAI 兼容）
DOUBAO_SEED_API_KEY = os.environ.get('DOUBAO_SEED_API_KEY', '483dda0a-1fdc-4f79-9827-977f90b3175a')
DOUBAO_SEED_BASE_URL = os.environ.get('DOUBAO_SEED_BASE_URL', 'https://ark.cn-beijing.volces.com/api/v3')
DOUBAO_SEED_MODEL_NAME = os.environ.get('DOUBAO_SEED_MODEL_NAME', 'doubao-seed-2-0-mini-260215')

# 当前使用的模型提供商，默认 DeepSeek（需配置 DEEPSEEK_API_KEY）
AI_MODEL_PROVIDER = os.environ.get('AI_MODEL_PROVIDER', 'deepseek')
# 聊天流式工具模式：native=bind_tools；json_protocol=仅当 AI_MODEL_PROVIDER=qwen2api 时生效（千问网页类网关无原生 tool 时用）；deepseek/doubao_seed 恒为 native
AI_CHAT_TOOL_MODE = os.environ.get('AI_CHAT_TOOL_MODE', 'native').strip().lower()
AI_SYSTEM_PROMPT = os.environ.get(
    'AI_SYSTEM_PROMPT',
    '你是一个专业的金融分析师，擅长对结构化数据进行分析并给出简洁结论。',
)
AI_DEFAULT_PROMPT = os.environ.get(
    'AI_DEFAULT_PROMPT',
    '请根据以下数据进行分析，输出简洁的中文结果：\n{data}',
)
# 多轮聊天：客户端传入的历史里，工具原始返回（往往很大）是否压缩后再送入模型。
# max_chars=0 表示整段工具结果一律用占位说明替换，仅保留 user/assistant 自然语言与 tool_call_id 链。
# max_chars>0 时保留内容前 max_chars 个字符，超出部分省略并标注原长度。
AI_CHAT_HISTORY_TOOL_MAX_CHARS = int(os.environ.get('AI_CHAT_HISTORY_TOOL_MAX_CHARS', '0'))
AI_CHAT_HISTORY_TOOL_PLACEHOLDER = os.environ.get(
    'AI_CHAT_HISTORY_TOOL_PLACEHOLDER',
    '（本段为工具返回的原始数据，已在会话历史中省略以避免超长上下文；原数据约 {chars} 字符。如需基于该数据继续分析，请说明意图以便重新调用工具查询。）',
)
# 工具结果与 SSE tool_card、会话库 tool_data、GitHub 同步 Markdown 共用同一上限（减轻端上加载历史与会仓库体积）。
# 0 表示不截断。模型推理仍使用完整工具返回（ToolMessage）；仅对外持久化与展示路径按此字段截断。
AI_TOOL_CARD_RESULT_MAX_CHARS = int(
    os.environ.get('AI_TOOL_CARD_RESULT_MAX_CHARS', '4096')
)
AI_GITHUB_SYNC_ENABLED = os.environ.get('AI_GITHUB_SYNC_ENABLED', '').strip().lower() in ('1', 'true', 'yes', 'on')
AI_GITHUB_TOKEN = os.environ.get('AI_GITHUB_TOKEN', '').strip()
AI_GITHUB_SYNC_REPO = os.environ.get('AI_GITHUB_SYNC_REPO', 'huang1125677925/mybook').strip()
AI_GITHUB_SYNC_BRANCH = os.environ.get('AI_GITHUB_SYNC_BRANCH', 'main').strip()
AI_GITHUB_SYNC_PATH_TEMPLATE = os.environ.get(
    'AI_GITHUB_SYNC_PATH_TEMPLATE',
    'ai_answers/{date}-{time}-{question}.md',
).strip()

# 数据更新频率（秒）
DATA_UPDATE_INTERVAL = int(os.environ.get('DATA_UPDATE_INTERVAL', 60))

# 股票数据缓存时间（秒）
STOCK_CACHE_TIMEOUT = int(os.environ.get('STOCK_CACHE_TIMEOUT', 300))
STOCK_REQUEST_TIMEOUT = int(os.environ.get('STOCK_REQUEST_TIMEOUT', 30))
STOCK_MAX_RETRIES = int(os.environ.get('STOCK_MAX_RETRIES', 3))

# API限流配置
API_RATE_LIMIT = os.environ.get('API_RATE_LIMIT', '100/hour')

# 创建日志目录
log_dir = BASE_DIR / 'logs'
log_dir.mkdir(exist_ok=True)

# 注释迁移插件配置
DCM_COMMENT_KEY = 'verbose_name'  # 将字段 verbose_name 作为列注释来源
DCM_TABLE_COMMENT_KEY = 'verbose_name'  # 将模型 Meta.verbose_name 作为表注释来源
DCM_COMMENT_APP = ['indival_stock_data']  # 仅迁移该 app 的注释
