# Generated by Django 4.2.7 on 2025-09-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MarketSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="日期")),
                ("total_stocks", models.IntegerField(verbose_name="股票总数")),
                ("rising_stocks", models.IntegerField(verbose_name="上涨股票数")),
                ("falling_stocks", models.IntegerField(verbose_name="下跌股票数")),
                ("flat_stocks", models.IntegerField(verbose_name="平盘股票数")),
                ("total_volume", models.BigIntegerField(verbose_name="总成交量")),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="总成交额"
                    ),
                ),
                (
                    "avg_change_percent",
                    models.DecimalField(
                        decimal_places=3, max_digits=8, verbose_name="平均涨跌幅(%)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "市场摘要",
                "verbose_name_plural": "市场摘要",
                "db_table": "market_summary",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="StockInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=10, unique=True, verbose_name="股票代码"),
                ),
                ("name", models.CharField(max_length=50, verbose_name="股票名称")),
                (
                    "industry",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="所属行业"
                    ),
                ),
                (
                    "total_shares",
                    models.BigIntegerField(blank=True, null=True, verbose_name="总股本"),
                ),
                (
                    "circulating_shares",
                    models.BigIntegerField(blank=True, null=True, verbose_name="流通股本"),
                ),
                (
                    "list_date",
                    models.DateField(blank=True, null=True, verbose_name="上市日期"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "股票基本信息",
                "verbose_name_plural": "股票基本信息",
                "db_table": "stock_info",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="StockRealtime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(db_index=True, max_length=10, verbose_name="股票代码"),
                ),
                ("name", models.CharField(max_length=50, verbose_name="股票名称")),
                (
                    "latest_price",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="最新价"
                    ),
                ),
                (
                    "change_percent",
                    models.DecimalField(
                        decimal_places=3, max_digits=8, verbose_name="涨跌幅(%)"
                    ),
                ),
                (
                    "change_amount",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="涨跌额"
                    ),
                ),
                ("volume", models.BigIntegerField(verbose_name="成交量(手)")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="成交额(元)"
                    ),
                ),
                (
                    "amplitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=8,
                        null=True,
                        verbose_name="振幅(%)",
                    ),
                ),
                (
                    "high",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="最高价",
                    ),
                ),
                (
                    "low",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="最低价",
                    ),
                ),
                (
                    "open_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="开盘价",
                    ),
                ),
                (
                    "close_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="昨收价",
                    ),
                ),
                (
                    "turnover_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=8,
                        null=True,
                        verbose_name="换手率(%)",
                    ),
                ),
                (
                    "pe_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="市盈率",
                    ),
                ),
                (
                    "pb_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="市净率",
                    ),
                ),
                (
                    "market_cap",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="总市值",
                    ),
                ),
                (
                    "circulating_market_cap",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="流通市值",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="数据时间"),
                ),
            ],
            options={
                "verbose_name": "股票实时行情",
                "verbose_name_plural": "股票实时行情",
                "db_table": "stock_realtime",
                "ordering": ["-timestamp", "code"],
                "indexes": [
                    models.Index(
                        fields=["code", "-timestamp"],
                        name="stock_realt_code_cf5be8_idx",
                    ),
                    models.Index(
                        fields=["-timestamp"], name="stock_realt_timesta_3a48fd_idx"
                    ),
                ],
            },
        ),
    ]
