# Generated by Django 4.2.7 on 2025-10-15 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("industry_stock_data", "0003_industrysector_change_amount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndustrySectorFundFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="交易日期")),
                (
                    "main_net_inflow_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="主力净流入-净额"
                    ),
                ),
                (
                    "main_net_inflow_ratio",
                    models.DecimalField(
                        decimal_places=3, max_digits=8, verbose_name="主力净流入-净占比(%)"
                    ),
                ),
                (
                    "super_large_net_inflow_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="超大单净流入-净额"
                    ),
                ),
                (
                    "super_large_net_inflow_ratio",
                    models.DecimalField(
                        decimal_places=3, max_digits=8, verbose_name="超大单净流入-净占比(%)"
                    ),
                ),
                (
                    "large_net_inflow_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="大单净流入-净额"
                    ),
                ),
                (
                    "large_net_inflow_ratio",
                    models.DecimalField(
                        decimal_places=3, max_digits=8, verbose_name="大单净流入-净占比(%)"
                    ),
                ),
                (
                    "medium_net_inflow_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="中单净流入-净额"
                    ),
                ),
                (
                    "medium_net_inflow_ratio",
                    models.DecimalField(
                        decimal_places=3, max_digits=8, verbose_name="中单净流入-净占比(%)"
                    ),
                ),
                (
                    "small_net_inflow_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="小单净流入-净额"
                    ),
                ),
                (
                    "small_net_inflow_ratio",
                    models.DecimalField(
                        decimal_places=3, max_digits=8, verbose_name="小单净流入-净占比(%)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fund_flow_data",
                        to="industry_stock_data.industrysector",
                        verbose_name="所属板块",
                    ),
                ),
            ],
            options={
                "verbose_name": "行业板块资金流数据",
                "verbose_name_plural": "行业板块资金流数据",
                "db_table": "industry_sector_fund_flow",
                "ordering": ["-date", "sector"],
                "indexes": [
                    models.Index(
                        fields=["sector", "-date"],
                        name="industry_se_sector__8d84fe_idx",
                    ),
                    models.Index(fields=["-date"], name="industry_se_date_f1b661_idx"),
                ],
                "unique_together": {("sector", "date")},
            },
        ),
    ]
