# Generated by Django 4.2.7 on 2025-09-16 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IndividualStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=10, unique=True, verbose_name="股票代码"),
                ),
                ("name", models.CharField(max_length=50, verbose_name="股票名称")),
                (
                    "industry",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="所属行业"
                    ),
                ),
                (
                    "total_shares",
                    models.BigIntegerField(blank=True, null=True, verbose_name="总股本"),
                ),
                (
                    "circulating_shares",
                    models.BigIntegerField(blank=True, null=True, verbose_name="流通股本"),
                ),
                (
                    "list_date",
                    models.DateField(blank=True, null=True, verbose_name="上市日期"),
                ),
                (
                    "pe_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="市盈率",
                    ),
                ),
                (
                    "pb_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="市净率",
                    ),
                ),
                (
                    "total_market_cap",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="总市值",
                    ),
                ),
                (
                    "circulating_market_cap",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="流通市值",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "个股基本信息",
                "verbose_name_plural": "个股基本信息",
                "db_table": "individual_stock",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="IndividualStockRealtime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "latest_price",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="最新价"
                    ),
                ),
                (
                    "change_percent",
                    models.DecimalField(
                        decimal_places=3, max_digits=8, verbose_name="涨跌幅(%)"
                    ),
                ),
                (
                    "change_amount",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="涨跌额"
                    ),
                ),
                ("volume", models.BigIntegerField(verbose_name="成交量(手)")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="成交额(元)"
                    ),
                ),
                (
                    "amplitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=8,
                        null=True,
                        verbose_name="振幅(%)",
                    ),
                ),
                (
                    "high",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="最高价",
                    ),
                ),
                (
                    "low",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="最低价",
                    ),
                ),
                (
                    "open_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="开盘价",
                    ),
                ),
                (
                    "close_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="昨收价",
                    ),
                ),
                (
                    "turnover_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=8,
                        null=True,
                        verbose_name="换手率(%)",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="数据时间"),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="realtime_data",
                        to="indival_stock_data.individualstock",
                        verbose_name="所属股票",
                    ),
                ),
            ],
            options={
                "verbose_name": "个股实时行情",
                "verbose_name_plural": "个股实时行情",
                "db_table": "individual_stock_realtime",
                "ordering": ["-timestamp", "stock"],
                "indexes": [
                    models.Index(
                        fields=["stock", "-timestamp"],
                        name="individual__stock_i_7f39f9_idx",
                    ),
                    models.Index(
                        fields=["-timestamp"], name="individual__timesta_fba328_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="IndividualStockDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="交易日期")),
                (
                    "open_price",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="开盘价"
                    ),
                ),
                (
                    "close_price",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="收盘价"
                    ),
                ),
                (
                    "high_price",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="最高价"
                    ),
                ),
                (
                    "low_price",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="最低价"
                    ),
                ),
                (
                    "change_percent",
                    models.DecimalField(
                        decimal_places=3, max_digits=8, verbose_name="涨跌幅(%)"
                    ),
                ),
                (
                    "change_amount",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="涨跌额"
                    ),
                ),
                ("volume", models.BigIntegerField(verbose_name="成交量(手)")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="成交额(元)"
                    ),
                ),
                (
                    "amplitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=8,
                        null=True,
                        verbose_name="振幅(%)",
                    ),
                ),
                (
                    "turnover_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=8,
                        null=True,
                        verbose_name="换手率(%)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_data",
                        to="indival_stock_data.individualstock",
                        verbose_name="所属股票",
                    ),
                ),
            ],
            options={
                "verbose_name": "个股日频数据",
                "verbose_name_plural": "个股日频数据",
                "db_table": "individual_stock_daily",
                "ordering": ["-date", "stock"],
                "indexes": [
                    models.Index(
                        fields=["stock", "-date"], name="individual__stock_i_ea15e0_idx"
                    ),
                    models.Index(fields=["-date"], name="individual__date_80a81a_idx"),
                ],
                "unique_together": {("stock", "date")},
            },
        ),
    ]
