# Generated by Django 4.2.7 on 2025-09-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "indival_stock_data",
            "0002_individualstock_amount_individualstock_amplitude_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="StrategyResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "strategy_name",
                    models.CharField(max_length=100, verbose_name="策略名称"),
                ),
                ("strategy_description", models.TextField(verbose_name="策略描述")),
                (
                    "strategy_result",
                    models.TextField(help_text="JSON格式存储策略选股结果", verbose_name="策略结果"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "策略选股结果",
                "verbose_name_plural": "策略选股结果",
                "db_table": "strategy_result",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["strategy_name"], name="strategy_re_strateg_a8fd4f_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="strategy_re_created_586dc2_idx"
                    ),
                ],
            },
        ),
    ]
