# Generated by Django 4.2.7 on 2025-10-11 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("indival_stock_data", "0003_strategyresult"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerformanceReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_date",
                    models.CharField(
                        help_text="格式：YYYYMMDD，如20200331",
                        max_length=8,
                        verbose_name="报告期",
                    ),
                ),
                (
                    "earnings_per_share",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="每股收益",
                    ),
                ),
                (
                    "operating_revenue",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="营业收入",
                    ),
                ),
                (
                    "operating_revenue_last_year",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="营业收入-去年同期",
                    ),
                ),
                (
                    "operating_revenue_growth_rate",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="营业收入-同比增长"
                    ),
                ),
                (
                    "operating_revenue_quarter_growth",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="营业收入-季度环比增长",
                    ),
                ),
                (
                    "net_profit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="净利润",
                    ),
                ),
                (
                    "net_profit_last_year",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="净利润-去年同期",
                    ),
                ),
                (
                    "net_profit_growth_rate",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="净利润-同比增长"
                    ),
                ),
                (
                    "net_profit_quarter_growth",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="净利润-季度环比增长",
                    ),
                ),
                (
                    "net_assets_per_share",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="每股净资产",
                    ),
                ),
                (
                    "roe",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        verbose_name="净资产收益率",
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="所处行业"
                    ),
                ),
                (
                    "announcement_date",
                    models.DateField(blank=True, null=True, verbose_name="公告日期"),
                ),
                (
                    "market_board",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="市场板块"
                    ),
                ),
                (
                    "security_type",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="证券类型"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_reports",
                        to="indival_stock_data.individualstock",
                        verbose_name="所属股票",
                    ),
                ),
            ],
            options={
                "verbose_name": "业绩快报",
                "verbose_name_plural": "业绩快报",
                "db_table": "performance_report",
                "ordering": ["-report_date", "stock"],
                "indexes": [
                    models.Index(
                        fields=["stock", "-report_date"],
                        name="performance_stock_i_bacc4a_idx",
                    ),
                    models.Index(
                        fields=["-report_date"], name="performance_report__0d1179_idx"
                    ),
                    models.Index(
                        fields=["announcement_date"],
                        name="performance_announc_03b60d_idx",
                    ),
                ],
                "unique_together": {("stock", "report_date")},
            },
        ),
    ]
