# Generated by Django 4.2.7 on 2025-10-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indival_stock_data", "0004_performancereport"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="performancereport",
            name="market_board",
        ),
        migrations.RemoveField(
            model_name="performancereport",
            name="net_profit_last_year",
        ),
        migrations.RemoveField(
            model_name="performancereport",
            name="operating_revenue_last_year",
        ),
        migrations.RemoveField(
            model_name="performancereport",
            name="security_type",
        ),
        migrations.AddField(
            model_name="performancereport",
            name="gross_profit_margin",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=8,
                null=True,
                verbose_name="销售毛利率",
            ),
        ),
        migrations.AddField(
            model_name="performancereport",
            name="operating_cash_flow_per_share",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=10,
                null=True,
                verbose_name="每股经营现金流量",
            ),
        ),
        migrations.AlterField(
            model_name="performancereport",
            name="announcement_date",
            field=models.DateField(blank=True, null=True, verbose_name="最新公告日期"),
        ),
        migrations.AlterField(
            model_name="performancereport",
            name="net_profit_growth_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="净利润-同比增长",
            ),
        ),
        migrations.AlterField(
            model_name="performancereport",
            name="operating_revenue",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                verbose_name="营业总收入",
            ),
        ),
        migrations.AlterField(
            model_name="performancereport",
            name="operating_revenue_growth_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="营业总收入-同比增长",
            ),
        ),
        migrations.AlterField(
            model_name="performancereport",
            name="operating_revenue_quarter_growth",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="营业总收入-季度环比增长",
            ),
        ),
    ]
