# Generated by Django 4.2.7 on 2025-10-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "indival_stock_data",
            "0006_alter_performancereport_earnings_per_share_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="performancereport",
            name="gross_profit_margin",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=12,
                null=True,
                verbose_name="销售毛利率(%)",
            ),
        ),
        migrations.AlterField(
            model_name="performancereport",
            name="roe",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=12,
                null=True,
                verbose_name="净资产收益率(%)",
            ),
        ),
    ]
