# Generated by Django 4.2.7 on 2025-10-19 01:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indival_stock_data", "0008_incomestatement_cashflowstatement_balancesheet"),
    ]

    operations = [
        migrations.AddField(
            model_name="individualstock",
            name="index_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SH_MAIN", "上证主板"),
                    ("SZ_MAIN", "深证主板"),
                    ("SZ_SME", "深证中小板"),
                    ("SZ_GEM", "深证创业板"),
                    ("BJ_MAIN", "北交所主板"),
                    ("SH_INDEX", "上证指数"),
                    ("SZ_INDEX", "深证指数"),
                    ("CSI_INDEX", "中证指数"),
                    ("OTHER", "其他"),
                ],
                max_length=20,
                null=True,
                verbose_name="指数类型",
            ),
        ),
    ]
