# Generated by Django 4.2.7 on 2025-10-19 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("indival_stock_data", "0009_individualstock_index_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pattern_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BREAKOUT", "突破形态"),
                            ("REVERSAL", "反转形态"),
                            ("CONSOLIDATION", "整理形态"),
                            ("HEAD_SHOULDERS", "头肩形态"),
                            ("DOUBLE_TOP", "双顶形态"),
                            ("DOUBLE_BOTTOM", "双底形态"),
                            ("TRIANGLE", "三角形态"),
                            ("FLAG", "旗形形态"),
                            ("WEDGE", "楔形形态"),
                            ("CHANNEL", "通道形态"),
                            ("OTHER", "其他形态"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="形态类型",
                    ),
                ),
                (
                    "technical_indicator_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MACD_BULLISH", "MACD多头"),
                            ("MACD_BEARISH", "MACD空头"),
                            ("RSI_OVERSOLD", "RSI超卖"),
                            ("RSI_OVERBOUGHT", "RSI超买"),
                            ("KDJ_GOLDEN_CROSS", "KDJ金叉"),
                            ("KDJ_DEATH_CROSS", "KDJ死叉"),
                            ("MA_BULLISH", "均线多头排列"),
                            ("MA_BEARISH", "均线空头排列"),
                            ("BOLL_UPPER", "布林上轨"),
                            ("BOLL_LOWER", "布林下轨"),
                            ("VOLUME_SURGE", "放量突破"),
                            ("VOLUME_SHRINK", "缩量整理"),
                            ("OTHER", "其他指标"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="技术指标类型",
                    ),
                ),
                (
                    "stock_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BLUE_CHIP", "蓝筹股"),
                            ("GROWTH", "成长股"),
                            ("VALUE", "价值股"),
                            ("SMALL_CAP", "小盘股"),
                            ("MID_CAP", "中盘股"),
                            ("LARGE_CAP", "大盘股"),
                            ("CONCEPT", "概念股"),
                            ("THEME", "题材股"),
                            ("ST", "ST股票"),
                            ("NEW_STOCK", "次新股"),
                            ("DIVIDEND", "高股息"),
                            ("OTHER", "其他类型"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="股票类型",
                    ),
                ),
                (
                    "market_cap_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MEGA_CAP", "超大盘股(>1000亿)"),
                            ("LARGE_CAP", "大盘股(300-1000亿)"),
                            ("MID_CAP", "中盘股(100-300亿)"),
                            ("SMALL_CAP", "小盘股(50-100亿)"),
                            ("MICRO_CAP", "微盘股(<50亿)"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="市值大小类型",
                    ),
                ),
                (
                    "pe_range_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NEGATIVE", "负PE"),
                            ("LOW", "低PE(0-15)"),
                            ("MODERATE", "适中PE(15-25)"),
                            ("HIGH", "高PE(25-50)"),
                            ("VERY_HIGH", "极高PE(>50)"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="PE区间类型",
                    ),
                ),
                (
                    "pb_range_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("VERY_LOW", "极低PB(<1)"),
                            ("LOW", "低PB(1-2)"),
                            ("MODERATE", "适中PB(2-3)"),
                            ("HIGH", "高PB(3-5)"),
                            ("VERY_HIGH", "极高PB(>5)"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="PB区间类型",
                    ),
                ),
                (
                    "industry_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TECHNOLOGY", "科技行业"),
                            ("FINANCE", "金融行业"),
                            ("HEALTHCARE", "医疗健康"),
                            ("CONSUMER", "消费行业"),
                            ("INDUSTRIAL", "工业制造"),
                            ("ENERGY", "能源行业"),
                            ("MATERIALS", "原材料"),
                            ("UTILITIES", "公用事业"),
                            ("REAL_ESTATE", "房地产"),
                            ("TELECOM", "电信服务"),
                            ("OTHER", "其他行业"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="行业类型",
                    ),
                ),
                (
                    "volume_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("VOLUME_SURGE", "放量"),
                            ("VOLUME_NORMAL", "正常量"),
                            ("VOLUME_SHRINK", "缩量"),
                            ("VOLUME_EXTREME", "极量"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="成交量类型",
                    ),
                ),
                (
                    "volatility_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LOW_VOLATILITY", "低波动"),
                            ("MODERATE_VOLATILITY", "中等波动"),
                            ("HIGH_VOLATILITY", "高波动"),
                            ("EXTREME_VOLATILITY", "极端波动"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="波动率类型",
                    ),
                ),
                (
                    "trend_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("STRONG_UPTREND", "强势上涨"),
                            ("WEAK_UPTREND", "弱势上涨"),
                            ("SIDEWAYS", "横盘整理"),
                            ("WEAK_DOWNTREND", "弱势下跌"),
                            ("STRONG_DOWNTREND", "强势下跌"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="趋势类型",
                    ),
                ),
                (
                    "tag_date",
                    models.DateField(help_text="标记生成的日期", verbose_name="标记日期"),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True, help_text="标记的详细说明", null=True, verbose_name="备注"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_tags",
                        to="indival_stock_data.individualstock",
                        verbose_name="所属股票",
                    ),
                ),
            ],
            options={
                "verbose_name": "股票标记",
                "verbose_name_plural": "股票标记",
                "db_table": "stock_tag",
                "ordering": ["-tag_date", "stock"],
                "indexes": [
                    models.Index(
                        fields=["stock", "-tag_date"],
                        name="stock_tag_stock_i_5c1da7_idx",
                    ),
                    models.Index(
                        fields=["-tag_date"], name="stock_tag_tag_dat_4ba8bf_idx"
                    ),
                    models.Index(
                        fields=["pattern_type"], name="stock_tag_pattern_60babe_idx"
                    ),
                    models.Index(
                        fields=["technical_indicator_type"],
                        name="stock_tag_technic_b5a36e_idx",
                    ),
                    models.Index(
                        fields=["stock_type"], name="stock_tag_stock_t_b1f6c5_idx"
                    ),
                    models.Index(
                        fields=["market_cap_type"], name="stock_tag_market__d21a6a_idx"
                    ),
                    models.Index(
                        fields=["pe_range_type"], name="stock_tag_pe_rang_3cfaed_idx"
                    ),
                    models.Index(
                        fields=["pb_range_type"], name="stock_tag_pb_rang_9a02d2_idx"
                    ),
                    models.Index(
                        fields=["industry_type"], name="stock_tag_industr_87eaad_idx"
                    ),
                    models.Index(
                        fields=["volume_type"], name="stock_tag_volume__4a942b_idx"
                    ),
                    models.Index(
                        fields=["volatility_type"], name="stock_tag_volatil_273709_idx"
                    ),
                    models.Index(
                        fields=["trend_type"], name="stock_tag_trend_t_dfc2d7_idx"
                    ),
                ],
                "unique_together": {("stock", "tag_date")},
            },
        ),
    ]
