# Generated by Django 4.2.7 on 2025-10-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indival_stock_data", "0010_stocktag"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stocktag",
            options={
                "ordering": ["-created_at", "stock"],
                "verbose_name": "股票标记",
                "verbose_name_plural": "股票标记",
            },
        ),
        migrations.RemoveIndex(
            model_name="stocktag",
            name="stock_tag_stock_i_5c1da7_idx",
        ),
        migrations.RemoveIndex(
            model_name="stocktag",
            name="stock_tag_tag_dat_4ba8bf_idx",
        ),
        migrations.AlterUniqueTogether(
            name="stocktag",
            unique_together={("stock",)},
        ),
        migrations.AlterField(
            model_name="stocktag",
            name="pattern_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BREAKOUT", "突破形态"),
                    ("REVERSAL", "反转形态"),
                    ("CONSOLIDATION", "整理形态"),
                    ("HEAD_SHOULDERS", "头肩形态"),
                    ("DOUBLE_TOP", "双顶形态"),
                    ("DOUBLE_BOTTOM", "双底形态"),
                    ("TRIANGLE", "三角形态"),
                    ("FLAG", "旗形形态"),
                    ("WEDGE", "楔形形态"),
                    ("CHANNEL", "通道形态"),
                    ("BOX_BREAKOUT", "箱型突破"),
                    ("OTHER", "其他形态"),
                ],
                max_length=20,
                null=True,
                verbose_name="形态类型",
            ),
        ),
        migrations.AddIndex(
            model_name="stocktag",
            index=models.Index(
                fields=["stock", "-created_at"], name="stock_tag_stock_i_e18c4e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stocktag",
            index=models.Index(
                fields=["-created_at"], name="stock_tag_created_293658_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="stocktag",
            name="remarks",
        ),
        migrations.RemoveField(
            model_name="stocktag",
            name="tag_date",
        ),
    ]
