# Generated by Django 4.2.7 on 2025-11-13 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("indival_stock_data", "0011_alter_stocktag_options_and_more"),
    ]

    operations = [
        # 数据库中已存在 dc_concept 列，避免重复添加导致错误。
        # 使用 SeparateDatabaseAndState 只更新迁移状态，不执行数据库操作。
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="individualstock",
                    name="dc_concept",
                    field=models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="东财概念"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IndividualStockWeekly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="周周期日期")),
                (
                    "open_price",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="开盘价"
                    ),
                ),
                (
                    "close_price",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="收盘价"
                    ),
                ),
                (
                    "high_price",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="最高价"
                    ),
                ),
                (
                    "low_price",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="最低价"
                    ),
                ),
                (
                    "change_percent",
                    models.DecimalField(
                        decimal_places=3, max_digits=8, verbose_name="涨跌幅(%)"
                    ),
                ),
                (
                    "change_amount",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="涨跌额"
                    ),
                ),
                ("volume", models.BigIntegerField(verbose_name="成交量(手)")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="成交额(元)"
                    ),
                ),
                (
                    "amplitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=8,
                        null=True,
                        verbose_name="振幅(%)",
                    ),
                ),
                (
                    "turnover_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=8,
                        null=True,
                        verbose_name="换手率(%)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_data",
                        to="indival_stock_data.individualstock",
                        verbose_name="所属股票",
                    ),
                ),
            ],
            options={
                "verbose_name": "个股周频数据",
                "verbose_name_plural": "个股周频数据",
                "db_table": "individual_stock_weekly",
                "ordering": ["-date", "stock"],
                "indexes": [
                    models.Index(
                        fields=["stock", "-date"], name="individual__stock_i_d5224d_idx"
                    ),
                    models.Index(fields=["-date"], name="individual__date_992215_idx"),
                ],
                "unique_together": {("stock", "date")},
            },
        ),
    ]
